class_map = {
    "total": {
        1: "adrenal_gland_left",
        2: "adrenal_gland_right",
        3: "arteries",
        4: "autochthon_left",
        5: "autochthon_right",
        6: "brain",
        7: "clavicula_left",
        8: "clavicula_right",
        9: "colon",
        10: "duodenum",
        11: "esophagus",
        12: "face",
        13: "femur_left",
        14: "femur_right",
        15: "gallbladder",
        16: "gluteus_maximus_left",
        17: "gluteus_maximus_right",
        18: "gluteus_medius_left",
        19: "gluteus_medius_right",
        20: "gluteus_minimus_left",
        21: "gluteus_minimus_right",
        22: "heart_atrium_left",
        23: "heart_atrium_right",
        24: "heart_myocardium",
        25: "heart_ventricle_left",
        26: "heart_ventricle_right",
        27: "hip_left",
        28: "hip_right",
        29: "humerus_left",
        30: "humerus_right",
        31: "veins",
        32: "iliopsoas_left",
        33: "iliopsoas_right",
        34: "kidney_left",
        35: "kidney_right",
        36: "liver",
        37: "lung_lower_lobe_left",
        38: "lung_lower_lobe_right",
        39: "lung_middle_lobe_right",
        40: "lung_upper_lobe_left",
        41: "lung_upper_lobe_right",
        42: "pancreas",
        43: "portal_vein_and_splenic_vein",
        44: "pulmonary_artery",
        45: "rib_left_1",
        46: "rib_left_10",
        47: "rib_left_11",
        48: "rib_left_12",
        49: "rib_left_2",
        50: "rib_left_3",
        51: "rib_left_4",
        52: "rib_left_5",
        53: "rib_left_6",
        54: "rib_left_7",
        55: "rib_left_8",
        56: "rib_left_9",
        57: "rib_right_1",
        58: "rib_right_10",
        59: "rib_right_11",
        60: "rib_right_12",
        61: "rib_right_2",
        62: "rib_right_3",
        63: "rib_right_4",
        64: "rib_right_5",
        65: "rib_right_6",
        66: "rib_right_7",
        67: "rib_right_8",
        68: "rib_right_9",
        69: "sacrum",
        70: "scapula_left",
        71: "scapula_right",
        72: "small_bowel",
        73: "spleen",
        74: "stomach",
        75: "trachea",
        76: "urinary_bladder",
        77: "vertebrae_C1",
        78: "vertebrae_C2",
        79: "vertebrae_C3",
        80: "vertebrae_C4",
        81: "vertebrae_C5",
        82: "vertebrae_C6",
        83: "vertebrae_C7",
        84: "vertebrae_L1",
        85: "vertebrae_L2",
        86: "vertebrae_L3",
        87: "vertebrae_L4",
        88: "vertebrae_L5",
        89: "vertebrae_T1",
        90: "vertebrae_T10",
        91: "vertebrae_T11",
        92: "vertebrae_T12",
        93: "vertebrae_T2",
        94: "vertebrae_T3",
        95: "vertebrae_T4",
        96: "vertebrae_T5",
        97: "vertebrae_T6",
        98: "vertebrae_T7",
        99: "vertebrae_T8",
        100: "vertebrae_T9",
        101: "ureter_left",
        102: "ureter_right"
    },
    "lung_vessels": {
        1: "lung_vessels",
        2: "lung_trachea_bronchia"
    },
    "covid": {
        1: "lung_covid_infiltrate",
    },
    "cerebral_bleed": {
        1: "intracerebral_hemorrhage",
    },
    "hip_implant": {
        1: "hip_implant",
    },
    "coronary_arteries": {
        1: "coronary_arteries",
    },
    "test": {
        1: "carpal",
        2: "clavicula",
        3: "femur",
        4: "fibula",
        5: "humerus",
        6: "metacarpal",
        7: "metatarsal",
        8: "patella",
        9: "hips",
        10: "phalanges_hand",
        11: "radius",
        12: "ribs",
        13: "scapula",
        14: "skull",
        15: "spine",
        16: "sternum",
        17: "tarsal",
        18: "tibia",
        19: "phalanges_feet",
        20: "ulna"
    }
}


class_map_5_parts = {

    # 17 classes
    "class_map_part_organs": {
        1: "spleen",
        2: "kidney_right",
        3: "kidney_left",
        4: "gallbladder",
        5: "liver",
        6: "stomach",
        7: "aorta",
        8: "inferior_vena_cava",
        9: "portal_vein_and_splenic_vein",
        10: "pancreas",
        11: "adrenal_gland_right",
        12: "adrenal_gland_left",
        13: "lung_upper_lobe_left",
        14: "lung_lower_lobe_left",
        15: "lung_upper_lobe_right",
        16: "lung_middle_lobe_right",
        17: "lung_lower_lobe_right"
    },

    # 24 classes
    "class_map_part_vertebrae": {
        1: "vertebrae_L5",
        2: "vertebrae_L4",
        3: "vertebrae_L3",
        4: "vertebrae_L2",
        5: "vertebrae_L1",
        6: "vertebrae_T12",
        7: "vertebrae_T11",
        8: "vertebrae_T10",
        9: "vertebrae_T9",
        10: "vertebrae_T8",
        11: "vertebrae_T7",
        12: "vertebrae_T6",
        13: "vertebrae_T5",
        14: "vertebrae_T4",
        15: "vertebrae_T3",
        16: "vertebrae_T2",
        17: "vertebrae_T1",
        18: "vertebrae_C7",
        19: "vertebrae_C6",
        20: "vertebrae_C5",
        21: "vertebrae_C4",
        22: "vertebrae_C3",
        23: "vertebrae_C2",
        24: "vertebrae_C1"
    },

    # 18
    "class_map_part_cardiac": {
        1: "esophagus",
        2: "trachea",
        3: "heart_myocardium",
        4: "heart_atrium_left",
        5: "heart_ventricle_left",
        6: "heart_atrium_right",
        7: "heart_ventricle_right",
        8: "pulmonary_artery",
        9: "brain",
        10: "small_bowel",
        11: "duodenum",
        12: "colon",
        13: "urinary_bladder",
        14: "face",
        15: "arteries",
        16: "veins",
        17: "ureter_left",
        18: "ureter_right"
    },

    # 21
    "class_map_part_muscles": {
        1: "humerus_left",
        2: "humerus_right",
        3: "scapula_left",
        4: "scapula_right",
        5: "clavicula_left",
        6: "clavicula_right",
        7: "femur_left",
        8: "femur_right",
        9: "hip_left",
        10: "hip_right",
        11: "sacrum",
        12: "gluteus_maximus_left",
        13: "gluteus_maximus_right",
        14: "gluteus_medius_left",
        15: "gluteus_medius_right",
        16: "gluteus_minimus_left",
        17: "gluteus_minimus_right",
        18: "autochthon_left",
        19: "autochthon_right",
        20: "iliopsoas_left",
        21: "iliopsoas_right"
    },

    # 24 classes
    # 12. ribs start from vertebrae T12
    # Small subset of population (roughly 8%) have 13. rib below 12. rib
    #  (would start from L1 then)
    #  -> this has label rib_12
    # Even smaller subset (roughly 1%) has extra rib above 1. rib   ("Halsrippe")
    #  (the extra rib would start from C7)
    #  -> this has label rib_1
    #
    # Quite often only 11 ribs (12. ribs probably so small that not found). Those 
    # cases often wrongly segmented. 
    "class_map_part_ribs": {
        1: "rib_left_1",
        2: "rib_left_2",
        3: "rib_left_3",
        4: "rib_left_4",
        5: "rib_left_5",
        6: "rib_left_6",
        7: "rib_left_7",
        8: "rib_left_8",
        9: "rib_left_9",
        10: "rib_left_10",
        11: "rib_left_11",
        12: "rib_left_12",
        13: "rib_right_1",
        14: "rib_right_2",
        15: "rib_right_3",
        16: "rib_right_4",
        17: "rib_right_5",
        18: "rib_right_6",
        19: "rib_right_7",
        20: "rib_right_8",
        21: "rib_right_9",
        22: "rib_right_10",
        23: "rib_right_11",
        24: "rib_right_12"
    },

    "test": class_map["test"]
}


map_taskid_to_partname = {
    251: "class_map_part_organs",
    252: "class_map_part_vertebrae",
    253: "class_map_part_cardiac",
    254: "class_map_part_muscles",
    255: "class_map_part_ribs",

    517: "test"
}

# pprint({idx:v for idx, (k, v) in enumerate(a.items())}, sort_dicts=False)
